package by.training.task03.controller.command;

public enum CommandName {
    BUBBLE_SORT, INSERTION_SORT, MERGE_SORT, SELECTION_SORT,
    SHELL_SORT, SHAKER_SORT, HASH_SORT, CHANGE_LANGUAGE, MATRIX_LOAD,
    MATRIX_MULTIPLY, MATRIX_SUM, MATRIX_SUBTRACT, HELP, WRONG_REQUEST
}
